HIGH_LEVEL_CATEGORIES = [
    'Active Life',
    'Arts & Entertainment',
    'Automotive',
    'Beauty & Spas',
    'Education',
    'Event Planning & Services',
    'Financial Services',
    'Food',
    'Health & Medical',
    'Home Services',
    'Real Estate',
    'Hotels & Travel',
    'Local Flavor',
    'Local Services',
    'Mass Media',
    'Nightlife',
    'Pets',
    'Professional Services',
    'Public Services & Government',
    'Religious Organizations',
    'Restaurants',
    'Shopping',
]